// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['DarkThemePref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['DarkThemePref']['Delete']();
}

export function Get() {
  return window['go']['core']['DarkThemePref']['Get']();
}

export function IsSet() {
  return window['go']['core']['DarkThemePref']['IsSet']();
}

export function Key() {
  return window['go']['core']['DarkThemePref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['DarkThemePref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['DarkThemePref']['Watch']();
}
