// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteUnusedMods(arg1, arg2) {
  return window['go']['core']['DbHelper']['DeleteUnusedMods'](arg1, arg2);
}

export function InsertMod(arg1) {
  return window['go']['core']['DbHelper']['InsertMod'](arg1);
}

export function SelectCharacterWithModsAndTags(arg1, arg2, arg3, arg4) {
  return window['go']['core']['DbHelper']['SelectCharacterWithModsAndTags'](arg1, arg2, arg3, arg4);
}

export function SelectCharactersByGame(arg1) {
  return window['go']['core']['DbHelper']['SelectCharactersByGame'](arg1);
}

export function SelectClosestCharacter(arg1, arg2) {
  return window['go']['core']['DbHelper']['SelectClosestCharacter'](arg1, arg2);
}

export function UpsertCharacter(arg1) {
  return window['go']['core']['DbHelper']['UpsertCharacter'](arg1);
}
