// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function CreatePlaylist(arg1:types.Game,arg2:string):Promise<void>;

export function DeleteModById(arg1:number):Promise<void>;

export function DeletePlaylistById(arg1:number):Promise<void>;

export function DeleteTextureById(arg1:number):Promise<void>;

export function DisableAllModsByGame(arg1:types.Game):Promise<void>;

export function EnableModById(arg1:boolean,arg2:number):Promise<void>;

export function EnableTextureById(arg1:boolean,arg2:number):Promise<void>;

export function InsertMod(arg1:types.Mod):Promise<number>;

export function InsertTexture(arg1:types.Texture):Promise<number>;

export function RenameMod(arg1:number,arg2:string):Promise<void>;

export function RenameTexture(arg1:number,arg2:string):Promise<void>;

export function SelectCharacterWithModsTagsAndTextures(arg1:types.Game,arg2:string,arg3:string,arg4:string):Promise<Array<types.CharacterWithModsAndTags>>;

export function SelectCharactersByGame(arg1:types.Game):Promise<Array<types.Character>>;

export function SelectClosestCharacter(arg1:string,arg2:types.Game):Promise<types.Character>;

export function SelectEnabledModsByGame(arg1:types.Game):Promise<Array<types.Mod>>;

export function SelectEnabledTexturesByModId(arg1:number):Promise<Array<types.Texture>>;

export function SelectModByCNameAndGame(arg1:string,arg2:string,arg3:number):Promise<types.Mod>;

export function SelectModById(arg1:number):Promise<types.Mod>;

export function SelectModsByCharacterName(arg1:string,arg2:types.Game):Promise<Array<types.Mod>>;

export function SelectModsByGbId(arg1:number):Promise<Array<types.Mod>>;

export function SelectPlaylistWithModsAndTags(arg1:types.Game):Promise<Array<types.PlaylistWithModsAndTags>>;

export function SelectTexturesByModId(arg1:number):Promise<Array<types.Texture>>;

export function SelecteTextureById(arg1:number):Promise<types.Texture>;

export function UpdateModGbId(arg1:number,arg2:number):Promise<void>;

export function UpdateModImages(arg1:number,arg2:Array<string>):Promise<void>;

export function UpdateModsEnabledFromSlice(arg1:Array<number>,arg2:types.Game):Promise<void>;

export function UpsertCharacter(arg1:types.Character):Promise<void>;
