// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function DeleteUnusedMods(arg1:Array<string>,arg2:types.Game):Promise<void>;

export function InsertMod(arg1:types.Mod):Promise<void>;

export function SelectCharacterWithModsAndTags(arg1:types.Game,arg2:string,arg3:string,arg4:string):Promise<Array<types.CharacterWithModsAndTags>>;

export function SelectCharactersByGame(arg1:types.Game):Promise<Array<types.Character>>;

export function SelectClosestCharacter(arg1:string,arg2:types.Game):Promise<types.Character>;

export function SelectModsByCharacterName(arg1:string,arg2:types.Game):Promise<Array<types.Mod>>;

export function UpsertCharacter(arg1:types.Character):Promise<void>;
