// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['DiscoverGamePref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['DiscoverGamePref']['Delete']();
}

export function Get() {
  return window['go']['core']['DiscoverGamePref']['Get']();
}

export function IsSet() {
  return window['go']['core']['DiscoverGamePref']['IsSet']();
}

export function Key() {
  return window['go']['core']['DiscoverGamePref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['DiscoverGamePref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['DiscoverGamePref']['Watch']();
}
