// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['core']['Downloader']['Delete'](arg1);
}

export function DeleteTexture(arg1) {
  return window['go']['core']['Downloader']['DeleteTexture'](arg1);
}

export function Download(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['core']['Downloader']['Download'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DownloadTexture(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['core']['Downloader']['DownloadTexture'](arg1, arg2, arg3, arg4, arg5);
}

export function GetQueue() {
  return window['go']['core']['Downloader']['GetQueue']();
}

export function RemoveFromQueue(arg1) {
  return window['go']['core']['Downloader']['RemoveFromQueue'](arg1);
}

export function Retry(arg1) {
  return window['go']['core']['Downloader']['Retry'](arg1);
}

export function Stop() {
  return window['go']['core']['Downloader']['Stop']();
}
