// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {core} from '../models';

export function Delete(arg1:number):Promise<void>;

export function Download(arg1:string,arg2:string,arg3:string,arg4:number,arg5:types.Game,arg6:number):Promise<void>;

export function GetQueue():Promise<{[key: string]: core.DLItem}>;

export function RemoveFromQueue(arg1:string):Promise<void>;

export function Retry(arg1:string):Promise<void>;

export function Stop():Promise<void>;
