// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Donwload(arg1:string,arg2:string,arg3:string,arg4:number,arg5:types.Game,arg6:number):Promise<void>;
