// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['core']['Downloader']['Delete'](arg1);
}

export function Download(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['core']['Downloader']['Download'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetQueue() {
  return window['go']['core']['Downloader']['GetQueue']();
}

export function Pause() {
  return window['go']['core']['Downloader']['Pause']();
}

export function RemoveFromQueue(arg1) {
  return window['go']['core']['Downloader']['RemoveFromQueue'](arg1);
}
