// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['EnabledPluginsPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['EnabledPluginsPref']['Delete']();
}

export function Get() {
  return window['go']['core']['EnabledPluginsPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['EnabledPluginsPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['EnabledPluginsPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['EnabledPluginsPref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['EnabledPluginsPref']['Watch']();
}
