// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['GenshinDirPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['GenshinDirPref']['Delete']();
}

export function Get() {
  return window['go']['core']['GenshinDirPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['GenshinDirPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['GenshinDirPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['GenshinDirPref']['Set'](arg1);
}
