// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['GenshinElementPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['GenshinElementPref']['Delete']();
}

export function Get() {
  return window['go']['core']['GenshinElementPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['GenshinElementPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['GenshinElementPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['GenshinElementPref']['Set'](arg1);
}
