// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue():Promise<Array<string>>;

export function Delete():Promise<void>;

export function Get():Promise<Array<string>>;

export function IsSet():Promise<boolean>;

export function Key():Promise<string>;

export function Set(arg1:Array<string>):Promise<void>;

export function Watch():Promise<any|any>;
