// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['HonkaiDirPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['HonkaiDirPref']['Delete']();
}

export function Get() {
  return window['go']['core']['HonkaiDirPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['HonkaiDirPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['HonkaiDirPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['HonkaiDirPref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['HonkaiDirPref']['Watch']();
}
