// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteKeymap(arg1) {
  return window['go']['core']['KeyMapper']['DeleteKeymap'](arg1);
}

export function DisableAllExcept(arg1) {
  return window['go']['core']['KeyMapper']['DisableAllExcept'](arg1);
}

export function GetKeyMap() {
  return window['go']['core']['KeyMapper']['GetKeyMap']();
}

export function GetKeymaps() {
  return window['go']['core']['KeyMapper']['GetKeymaps']();
}

export function Load(arg1) {
  return window['go']['core']['KeyMapper']['Load'](arg1);
}

export function LoadDefault() {
  return window['go']['core']['KeyMapper']['LoadDefault']();
}

export function LoadPrevious(arg1) {
  return window['go']['core']['KeyMapper']['LoadPrevious'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['core']['KeyMapper']['SaveConfig'](arg1);
}

export function Unload() {
  return window['go']['core']['KeyMapper']['Unload']();
}

export function Write(arg1, arg2, arg3) {
  return window['go']['core']['KeyMapper']['Write'](arg1, arg2, arg3);
}
