// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackups() {
  return window['go']['core']['KeyMapper']['GetBackups']();
}

export function GetKeyMap() {
  return window['go']['core']['KeyMapper']['GetKeyMap']();
}

export function Load(arg1) {
  return window['go']['core']['KeyMapper']['Load'](arg1);
}

export function SaveConfig() {
  return window['go']['core']['KeyMapper']['SaveConfig']();
}

export function Unload() {
  return window['go']['core']['KeyMapper']['Unload']();
}

export function Write(arg1, arg2) {
  return window['go']['core']['KeyMapper']['Write'](arg1, arg2);
}
