// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['MaxDownloadWorkersPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['MaxDownloadWorkersPref']['Delete']();
}

export function Get() {
  return window['go']['core']['MaxDownloadWorkersPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['MaxDownloadWorkersPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['MaxDownloadWorkersPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['MaxDownloadWorkersPref']['Set'](arg1);
}
