// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue():Promise<boolean>;

export function Delete():Promise<void>;

export function Get():Promise<boolean>;

export function IsSet():Promise<boolean>;

export function Key():Promise<string>;

export function Set(arg1:boolean):Promise<void>;
