// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['PlaylistGamePref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['PlaylistGamePref']['Delete']();
}

export function Get() {
  return window['go']['core']['PlaylistGamePref']['Get']();
}

export function IsSet() {
  return window['go']['core']['PlaylistGamePref']['IsSet']();
}

export function Key() {
  return window['go']['core']['PlaylistGamePref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['PlaylistGamePref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['PlaylistGamePref']['Watch']();
}
