// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['ServerPasswordPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['ServerPasswordPref']['Delete']();
}

export function Get() {
  return window['go']['core']['ServerPasswordPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['ServerPasswordPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['ServerPasswordPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['ServerPasswordPref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['ServerPasswordPref']['Watch']();
}
