// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function DefaultValue():Promise<number>;

export function Delete():Promise<void>;

export function Get():Promise<number>;

export function IsSet():Promise<boolean>;

export function Key():Promise<string>;

export function Set(arg1:number):Promise<void>;

export function Watch():Promise<any|context.CancelFunc>;
