// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['ServerPortPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['ServerPortPref']['Delete']();
}

export function Get() {
  return window['go']['core']['ServerPortPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['ServerPortPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['ServerPortPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['ServerPortPref']['Set'](arg1);
}
