// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['SortModPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['SortModPref']['Delete']();
}

export function Get() {
  return window['go']['core']['SortModPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['SortModPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['SortModPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['SortModPref']['Set'](arg1);
}
