// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['StartScreenPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['StartScreenPref']['Delete']();
}

export function Get() {
  return window['go']['core']['StartScreenPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['StartScreenPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['StartScreenPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['StartScreenPref']['Set'](arg1);
}
