// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {core} from '../models';

export function Sync(arg1:types.Game,arg2:core.SyncRequest):Promise<void>;
