// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunAll(arg1) {
  return window['go']['core']['SyncHelper']['RunAll'](arg1);
}

export function Sync(arg1, arg2) {
  return window['go']['core']['SyncHelper']['Sync'](arg1, arg2);
}
