// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['WuwaDirPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['WuwaDirPref']['Delete']();
}

export function Get() {
  return window['go']['core']['WuwaDirPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['WuwaDirPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['WuwaDirPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['WuwaDirPref']['Set'](arg1);
}
