// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['ZenlessElementPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['ZenlessElementPref']['Delete']();
}

export function Get() {
  return window['go']['core']['ZenlessElementPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['ZenlessElementPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['ZenlessElementPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['ZenlessElementPref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['ZenlessElementPref']['Watch']();
}
