// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Character struct {
	ID        int64
	Game      int64
	Name      string
	AvatarUrl string
	Element   string
	Flags     int64
}

type Inicache struct {
	ID    int64
	ModID int64
	Fname string
}

type Mod struct {
	ID             int64
	Fname          string
	Game           int64
	CharName       string
	CharID         int64
	Selected       bool
	PreviewImages  string
	GbID           sql.NullInt64
	ModLink        sql.NullString
	GbFileName     sql.NullString
	GbDownloadLink sql.NullString
}

type Playlist struct {
	ID           int64
	PlaylistName string
	Game         int64
}

type PlaylistModCrossRef struct {
	PlaylistID int64
	ModID      int64
}

type Tag struct {
	ModID   int64
	TagName string
}

type Texture struct {
	ID             int64
	ModID          int64
	Fname          string
	Selected       bool
	PreviewImages  string
	GbID           sql.NullInt64
	ModLink        sql.NullString
	GbFileName     sql.NullString
	GbDownloadLink sql.NullString
}
