// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AwaitCurrentJob(arg1) {
  return window['go']['core']['Generator']['AwaitCurrentJob'](arg1);
}

export function IsRunning(arg1) {
  return window['go']['core']['Generator']['IsRunning'](arg1);
}

export function Reload(arg1) {
  return window['go']['core']['Generator']['Reload'](arg1);
}
