// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['Oneko']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['Oneko']['Delete']();
}

export function Get() {
  return window['go']['core']['Oneko']['Get']();
}

export function IsSet() {
  return window['go']['core']['Oneko']['IsSet']();
}

export function Key() {
  return window['go']['core']['Oneko']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['Oneko']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['Oneko']['Watch']();
}
