// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['ServerAuthTypePref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['ServerAuthTypePref']['Delete']();
}

export function Get() {
  return window['go']['core']['ServerAuthTypePref']['Get']();
}

export function IsSet() {
  return window['go']['core']['ServerAuthTypePref']['IsSet']();
}

export function Key() {
  return window['go']['core']['ServerAuthTypePref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['ServerAuthTypePref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['ServerAuthTypePref']['Watch']();
}
