// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomCharacter(arg1, arg2, arg3, arg4) {
  return window['go']['core']['DbHelper']['CreateCustomCharacter'](arg1, arg2, arg3, arg4);
}

export function CreatePlaylist(arg1, arg2) {
  return window['go']['core']['DbHelper']['CreatePlaylist'](arg1, arg2);
}

export function DeleteCharacter(arg1, arg2, arg3) {
  return window['go']['core']['DbHelper']['DeleteCharacter'](arg1, arg2, arg3);
}

export function DeleteModById(arg1) {
  return window['go']['core']['DbHelper']['DeleteModById'](arg1);
}

export function DeletePlaylistById(arg1) {
  return window['go']['core']['DbHelper']['DeletePlaylistById'](arg1);
}

export function DeleteTextureById(arg1) {
  return window['go']['core']['DbHelper']['DeleteTextureById'](arg1);
}

export function DisableAllModsByGame(arg1) {
  return window['go']['core']['DbHelper']['DisableAllModsByGame'](arg1);
}

export function EnableModById(arg1, arg2) {
  return window['go']['core']['DbHelper']['EnableModById'](arg1, arg2);
}

export function EnableTextureById(arg1, arg2) {
  return window['go']['core']['DbHelper']['EnableTextureById'](arg1, arg2);
}

export function InsertMod(arg1) {
  return window['go']['core']['DbHelper']['InsertMod'](arg1);
}

export function InsertTexture(arg1) {
  return window['go']['core']['DbHelper']['InsertTexture'](arg1);
}

export function RenameMod(arg1, arg2) {
  return window['go']['core']['DbHelper']['RenameMod'](arg1, arg2);
}

export function RenameTexture(arg1, arg2) {
  return window['go']['core']['DbHelper']['RenameTexture'](arg1, arg2);
}

export function SelectCharacterWithModsTagsAndTextures(arg1, arg2, arg3, arg4) {
  return window['go']['core']['DbHelper']['SelectCharacterWithModsTagsAndTextures'](arg1, arg2, arg3, arg4);
}

export function SelectCharactersByGame(arg1) {
  return window['go']['core']['DbHelper']['SelectCharactersByGame'](arg1);
}

export function SelectClosestCharacter(arg1, arg2) {
  return window['go']['core']['DbHelper']['SelectClosestCharacter'](arg1, arg2);
}

export function SelectEnabledModsByGame(arg1) {
  return window['go']['core']['DbHelper']['SelectEnabledModsByGame'](arg1);
}

export function SelectEnabledTexturesByModId(arg1) {
  return window['go']['core']['DbHelper']['SelectEnabledTexturesByModId'](arg1);
}

export function SelectModByCNameAndGame(arg1, arg2, arg3) {
  return window['go']['core']['DbHelper']['SelectModByCNameAndGame'](arg1, arg2, arg3);
}

export function SelectModById(arg1) {
  return window['go']['core']['DbHelper']['SelectModById'](arg1);
}

export function SelectModsByCharacterName(arg1, arg2) {
  return window['go']['core']['DbHelper']['SelectModsByCharacterName'](arg1, arg2);
}

export function SelectModsByGbId(arg1) {
  return window['go']['core']['DbHelper']['SelectModsByGbId'](arg1);
}

export function SelectPlaylistWithModsAndTags(arg1) {
  return window['go']['core']['DbHelper']['SelectPlaylistWithModsAndTags'](arg1);
}

export function SelectTexturesByModId(arg1) {
  return window['go']['core']['DbHelper']['SelectTexturesByModId'](arg1);
}

export function SelecteTextureById(arg1) {
  return window['go']['core']['DbHelper']['SelecteTextureById'](arg1);
}

export function UpdateModGbId(arg1, arg2) {
  return window['go']['core']['DbHelper']['UpdateModGbId'](arg1, arg2);
}

export function UpdateModImages(arg1, arg2) {
  return window['go']['core']['DbHelper']['UpdateModImages'](arg1, arg2);
}

export function UpdateModsEnabledFromSlice(arg1, arg2) {
  return window['go']['core']['DbHelper']['UpdateModsEnabledFromSlice'](arg1, arg2);
}

export function UpdatePlaylistName(arg1, arg2) {
  return window['go']['core']['DbHelper']['UpdatePlaylistName'](arg1, arg2);
}

export function UpsertCharacter(arg1) {
  return window['go']['core']['DbHelper']['UpsertCharacter'](arg1);
}
