// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['WuwaElementPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['WuwaElementPref']['Delete']();
}

export function Get() {
  return window['go']['core']['WuwaElementPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['WuwaElementPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['WuwaElementPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['WuwaElementPref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['WuwaElementPref']['Watch']();
}
