// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['CleanModExportDirPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['CleanModExportDirPref']['Delete']();
}

export function Get() {
  return window['go']['core']['CleanModExportDirPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['CleanModExportDirPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['CleanModExportDirPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['CleanModExportDirPref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['CleanModExportDirPref']['Watch']();
}
