// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['ToastLevelPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['ToastLevelPref']['Delete']();
}

export function Get() {
  return window['go']['core']['ToastLevelPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['ToastLevelPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['ToastLevelPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['ToastLevelPref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['ToastLevelPref']['Watch']();
}
