// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['UseViewTransitions']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['UseViewTransitions']['Delete']();
}

export function Get() {
  return window['go']['core']['UseViewTransitions']['Get']();
}

export function IsSet() {
  return window['go']['core']['UseViewTransitions']['IsSet']();
}

export function Key() {
  return window['go']['core']['UseViewTransitions']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['UseViewTransitions']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['UseViewTransitions']['Watch']();
}
