// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['ZZZDirPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['ZZZDirPref']['Delete']();
}

export function Get() {
  return window['go']['core']['ZZZDirPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['ZZZDirPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['ZZZDirPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['ZZZDirPref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['ZZZDirPref']['Watch']();
}
