// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Listen(arg1) {
  return window['go']['server']['ServerManager']['Listen'](arg1);
}

export function Restart() {
  return window['go']['server']['ServerManager']['Restart']();
}

export function Running() {
  return window['go']['server']['ServerManager']['Running']();
}

export function Start() {
  return window['go']['server']['ServerManager']['Start']();
}

export function Stop() {
  return window['go']['server']['ServerManager']['Stop']();
}
