// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Listen(arg1:context.Context):Promise<void>;

export function Restart():Promise<void>;

export function Running():Promise<boolean>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
