// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Characters():Promise<Array<types.Character>>;

export function Elements():Promise<Array<string>>;

export function GetGame():Promise<types.Game>;

export function SkinId():Promise<number>;
