// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomCharacter(arg1, arg2, arg3, arg4) {
  return window['go']['dbh']['DbHelper']['CreateCustomCharacter'](arg1, arg2, arg3, arg4);
}

export function CreatePlaylist(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['CreatePlaylist'](arg1, arg2);
}

export function DeleteCharacter(arg1, arg2, arg3) {
  return window['go']['dbh']['DbHelper']['DeleteCharacter'](arg1, arg2, arg3);
}

export function DeleteModById(arg1) {
  return window['go']['dbh']['DbHelper']['DeleteModById'](arg1);
}

export function DeletePlaylistById(arg1) {
  return window['go']['dbh']['DbHelper']['DeletePlaylistById'](arg1);
}

export function DeleteTag(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['DeleteTag'](arg1, arg2);
}

export function DeleteTextureById(arg1) {
  return window['go']['dbh']['DbHelper']['DeleteTextureById'](arg1);
}

export function DeleteUnusedMods(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['DeleteUnusedMods'](arg1, arg2);
}

export function DeleteUnusedTextureFromMap(arg1) {
  return window['go']['dbh']['DbHelper']['DeleteUnusedTextureFromMap'](arg1);
}

export function InsertMod(arg1) {
  return window['go']['dbh']['DbHelper']['InsertMod'](arg1);
}

export function InsertTag(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['InsertTag'](arg1, arg2);
}

export function InsertTagForAllModsByCharacterIds(arg1, arg2, arg3) {
  return window['go']['dbh']['DbHelper']['InsertTagForAllModsByCharacterIds'](arg1, arg2, arg3);
}

export function InsertTexture(arg1) {
  return window['go']['dbh']['DbHelper']['InsertTexture'](arg1);
}

export function RenameMod(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['RenameMod'](arg1, arg2);
}

export function RenameTexture(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['RenameTexture'](arg1, arg2);
}

export function SelectCharacterWithModsTagsAndTextures(arg1, arg2, arg3, arg4) {
  return window['go']['dbh']['DbHelper']['SelectCharacterWithModsTagsAndTextures'](arg1, arg2, arg3, arg4);
}

export function SelectCharactersByGame(arg1) {
  return window['go']['dbh']['DbHelper']['SelectCharactersByGame'](arg1);
}

export function SelectClosestCharacter(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['SelectClosestCharacter'](arg1, arg2);
}

export function SelectEnabledModsByGame(arg1) {
  return window['go']['dbh']['DbHelper']['SelectEnabledModsByGame'](arg1);
}

export function SelectEnabledTexturesByModId(arg1) {
  return window['go']['dbh']['DbHelper']['SelectEnabledTexturesByModId'](arg1);
}

export function SelectModByFileCharacterGame(arg1, arg2, arg3) {
  return window['go']['dbh']['DbHelper']['SelectModByFileCharacterGame'](arg1, arg2, arg3);
}

export function SelectModById(arg1) {
  return window['go']['dbh']['DbHelper']['SelectModById'](arg1);
}

export function SelectModsByCharacterName(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['SelectModsByCharacterName'](arg1, arg2);
}

export function SelectModsByGbId(arg1) {
  return window['go']['dbh']['DbHelper']['SelectModsByGbId'](arg1);
}

export function SelectPlaylistWithModsAndTags(arg1) {
  return window['go']['dbh']['DbHelper']['SelectPlaylistWithModsAndTags'](arg1);
}

export function SelectTagsByModId(arg1) {
  return window['go']['dbh']['DbHelper']['SelectTagsByModId'](arg1);
}

export function SelectTextureById(arg1) {
  return window['go']['dbh']['DbHelper']['SelectTextureById'](arg1);
}

export function SelectTexturesByModId(arg1) {
  return window['go']['dbh']['DbHelper']['SelectTexturesByModId'](arg1);
}

export function UpdateDisableAllModsByGame(arg1) {
  return window['go']['dbh']['DbHelper']['UpdateDisableAllModsByGame'](arg1);
}

export function UpdateModEnabledById(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['UpdateModEnabledById'](arg1, arg2);
}

export function UpdateModGbId(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['UpdateModGbId'](arg1, arg2);
}

export function UpdateModImages(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['UpdateModImages'](arg1, arg2);
}

export function UpdateModsEnabledFromSlice(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['UpdateModsEnabledFromSlice'](arg1, arg2);
}

export function UpdatePlaylistName(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['UpdatePlaylistName'](arg1, arg2);
}

export function UpdateTagName(arg1, arg2, arg3) {
  return window['go']['dbh']['DbHelper']['UpdateTagName'](arg1, arg2, arg3);
}

export function UpdateTextureEnabledById(arg1, arg2) {
  return window['go']['dbh']['DbHelper']['UpdateTextureEnabledById'](arg1, arg2);
}

export function UpsertCharacter(arg1) {
  return window['go']['dbh']['DbHelper']['UpsertCharacter'](arg1);
}
