// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AwaitCurrentJob(arg1:types.Game):Promise<void>;

export function IsRunning(arg1:types.Game):Promise<boolean>;

export function Reload(arg1:types.Game):Promise<void>;
