// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultValue() {
  return window['go']['core']['SpaceSaverPref']['DefaultValue']();
}

export function Delete() {
  return window['go']['core']['SpaceSaverPref']['Delete']();
}

export function Get() {
  return window['go']['core']['SpaceSaverPref']['Get']();
}

export function IsSet() {
  return window['go']['core']['SpaceSaverPref']['IsSet']();
}

export function Key() {
  return window['go']['core']['SpaceSaverPref']['Key']();
}

export function Set(arg1) {
  return window['go']['core']['SpaceSaverPref']['Set'](arg1);
}

export function Watch() {
  return window['go']['core']['SpaceSaverPref']['Watch']();
}
