// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Categories(arg1:number):Promise<Array<api.CategoryListResponseItem>>;

export function CategoryContent(arg1:number,arg2:number,arg3:number,arg4:api.Sort,arg5:string,arg6:api.NameFilter,arg7:boolean,arg8:boolean,arg9:boolean,arg10:api.ReleaseType,arg11:api.ContentRating):Promise<api.CategoryResponse>;

export function ModPage(arg1:number):Promise<api.ModPageResponse>;
