// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Categories(arg1) {
  return window['go']['api']['GbApi']['Categories'](arg1);
}

export function CategoryContent(arg1, arg2, arg3, arg4) {
  return window['go']['api']['GbApi']['CategoryContent'](arg1, arg2, arg3, arg4);
}
