// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Categories(arg1:number):Promise<Array<api.CategoryListResponseItem>>;

export function CategoryContent(arg1:number,arg2:number,arg3:number,arg4:string):Promise<api.CategoryResponse>;
