// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Categories(arg1) {
  return window['go']['api']['GbApi']['Categories'](arg1);
}

export function CategoryContent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['api']['GbApi']['CategoryContent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function ModPage(arg1) {
  return window['go']['api']['GbApi']['ModPage'](arg1);
}

export function SubmitterItems(arg1) {
  return window['go']['api']['GbApi']['SubmitterItems'](arg1);
}

export function ToolPage(arg1) {
  return window['go']['api']['GbApi']['ToolPage'](arg1);
}
