// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Characters() {
  return window['go']['api']['leagueApi']['Characters']();
}

export function Elements() {
  return window['go']['api']['leagueApi']['Elements']();
}

export function GetGame() {
  return window['go']['api']['leagueApi']['GetGame']();
}

export function SkinId() {
  return window['go']['api']['leagueApi']['SkinId']();
}
