// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Characters() {
  return window['go']['api']['StarRailApi']['Characters']();
}

export function Elements() {
  return window['go']['api']['StarRailApi']['Elements']();
}

export function GetGame() {
  return window['go']['api']['StarRailApi']['GetGame']();
}

export function SkinId() {
  return window['go']['api']['StarRailApi']['SkinId']();
}
