// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePrefsDB() {
  return window['go']['main']['App']['ClosePrefsDB']();
}

export function DevModeEnabled() {
  return window['go']['main']['App']['DevModeEnabled']();
}

export function GetExclusionPaths() {
  return window['go']['main']['App']['GetExclusionPaths']();
}

export function GetExportDirectory() {
  return window['go']['main']['App']['GetExportDirectory']();
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function LoadPlugins() {
  return window['go']['main']['App']['LoadPlugins']();
}
