// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePrefsDB():Promise<void>;

export function DevModeEnabled():Promise<boolean>;

export function GetExclusionPaths():Promise<Array<string>>;

export function GetExportDirectory():Promise<string>;

export function GetPlugins():Promise<Array<string>>;

export function LoadPlugins():Promise<void>;

export function StopPlugins():Promise<void>;
