// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePrefsDB() {
  return window['go']['main']['App']['ClosePrefsDB']();
}

export function DevModeEnabled() {
  return window['go']['main']['App']['DevModeEnabled']();
}

export function ForcePanic() {
  return window['go']['main']['App']['ForcePanic']();
}

export function GetExclusionPaths() {
  return window['go']['main']['App']['GetExclusionPaths']();
}

export function GetExportDirectory() {
  return window['go']['main']['App']['GetExportDirectory']();
}

export function GetPluginsState() {
  return window['go']['main']['App']['GetPluginsState']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function LoadPlugins() {
  return window['go']['main']['App']['LoadPlugins']();
}

export function OpenDirectoryDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1, arg2);
}

export function OpenMultipleFilesDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenMultipleFilesDialog'](arg1, arg2);
}

export function StartPlugins() {
  return window['go']['main']['App']['StartPlugins']();
}

export function StopPlugins() {
  return window['go']['main']['App']['StopPlugins']();
}
