// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePrefsDB() {
  return window['go']['main']['App']['ClosePrefsDB']();
}

export function DevModeEnabled() {
  return window['go']['main']['App']['DevModeEnabled']();
}

export function GetExclusionPaths() {
  return window['go']['main']['App']['GetExclusionPaths']();
}

export function GetExportDirectory() {
  return window['go']['main']['App']['GetExportDirectory']();
}

export function GetPluginsState() {
  return window['go']['main']['App']['GetPluginsState']();
}

export function LoadPlugins() {
  return window['go']['main']['App']['LoadPlugins']();
}

export function StartPlugins() {
  return window['go']['main']['App']['StartPlugins']();
}

export function StopPlugins() {
  return window['go']['main']['App']['StopPlugins']();
}
