services:
  server:
    platform: linux/arm64
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - assets/
