version: "3"

tasks:
  dev:
    cmds:
      - cmd: ./bin/air/air_1.61.7_{{OS}}_{{ARCH}}
        platforms: [linux, darwin]
      - cmd: ./bin/air/air_1.61.7_{{OS}}_{{ARCH}}.exe
        platforms: [windows]
  tailwindcss:
    cmds:
      - cmd: ./bin/tailwindcss/tailwindcss_{{OS}}_{{ARCH}} -i "C:\Users\david\dev\go\skin-mod-manager\frontend\src\index.css" -o ./assets/style.css --minify
        platforms: [linux, darwin]
      - cmd: ./bin/tailwindcss/tailwindcss_{{OS}}_{{ARCH}}.exe -i "C:\Users\david\dev\go\skin-mod-manager\frontend\src\index.css" -o ./assets/style.css --minify
        platforms: [windows]
  templ:
    cmds:
      - cmd: ./bin/templ/templ_{{OS}}_{{ARCH}} generate
        platforms: [linux, darwin]
      - cmd: ./bin/templ/templ_{{OS}}_{{ARCH}}.exe generate
        platforms: [windows]
